name: CI
on:
  push:
    branches:
    - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy-sashboard:
    name: "Deploy trec-auto-judge.github.io/status to GitHub Pages"
    environment:
      name: GitHub Pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4     
      - name: 🧰 Setup GitHub Pages
        uses: actions/configure-pages@v5
      - name: 🏗️ Build the web app
        run: |
          render-health-status.py dist/status/index.html
      - name: 📤 Upload web app artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/
      - name: 🚀 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
